export const INDIAN_BOARDS = [
  "CBSE (Central Board of Secondary Education)",
  "CISCE / ICSE / ISC",
  "UP Board (UPMSP)",
  "Maharashtra Board (MSBSHSE)",
  "West Bengal Board (WBBSE / WBCHSE)",
  "Tamil Nadu Board (TNBSE / TNHSC)",
  "Karnataka Board (KSEEB / PUC Board)",
  "Rajasthan Board (RBSE)",
  "MP Board (MPBSE)",
  "Bihar Board (BSEB)",
  "Gujarat Board (GSEB)",
  "Jharkhand Board (JAC)",
  "Uttarakhand Board (UBSE)",
  "Chhattisgarh Board (CGBSE)",
  "Punjab Board (PSEB)",
  "Haryana Board (HBSE)",
  "HP Board (HPBOSE)",
  "J&K Board (JKBOSE)",
  "Goa Board (GBSHSE)",
  "Odisha Board (BSE / CHSE Odisha)",
  "AP Board (BSEAP / BIEAP)",
  "Telangana Board (BSETS / BIETELANGANA)",
  "Kerala Board (SCERT / DHSE Kerala)",
  "Assam Board (SEBA / AHSEC)",
  "Manipur Board (BSEM / COHSEM)",
  "Meghalaya Board (MBOSE)",
  "Nagaland Board (NBSE)",
  "Tripura Board (TBSE)",
  "Mizoram Board (MBSE)",
  "Arunachal Pradesh Board (SEBA affiliated)",
  "Sikkim Board (SBSE)",
  "NIOS (National Institute of Open Schooling)",
  "Other",
];
